### PR TITLE
Lead AliceExtension to be SF3 ready

### PR DESCRIPTION
**Pull request by gmorel**
#### Pain point

Currently the project is using an old version of [nelmio/alice](https://github.com/rezzza/alice-extension/blob/master/composer.json#L17) preventing it to be used on a SF3 app.

#### Proposal

- [x] Update  [nelmio/alice](https://github.com/nelmio/alice) to ~2.1
- [x] Use SF3 compatible factory service declaration
- [x] Force Fixture reference to be YAML compliant
- [x] Change composer.json with `"symfony/symfony": "~2.3|~3.0"`

### CODE REVIEW

**Comment by gmorel** [comment]
I got it working on my project test suite.
But I'm not using 100% of the project feature.

Since we are lacking of tests. Could someone test it on its project to make sure there is no major BC Break ?

**Comment by gmorel** [comment]
@tyx The PHP 5.4 build is failing during composer install
> Fatal error: Allowed memory size of 1073741824 bytes exhausted

Could you restart it ?

**Comment by tyx** [comment]
failed again :/

**Comment by tyx** [comment]
We should add a `composer self-update` in travis.yml

**Comment by gmorel** [comment]
Good catch !

**Comment by tyx** [comment]
I will give a try in one project

**Comment by tyx** [comment]
Ok in fact we no project with behat 3 and alice-extension :D So I guess we can merge and provide support if some bugs occur

**Comment by gmorel** [comment]
Ping @tyx

**Comment by shouze** [comment]
@gmorel some BC breaks? Which tag will it be?

**Comment by gmorel** [comment]
@shouze  From now on, we found no issue. Since we are not using 100% of the project features (ORM only) and since we have few test. The safest would be to bump a new major version ?

So end users would chose to use it or not. And the new version would be a clean Behat3 Symfony3 lib.

Currently we are using this step on DoctrineORM
```gherkin
Given I load "Vendor\My\Entity" fixtures where column "key" is the key:
```

What do you think ?

**Comment by tyx** [comment]
Yep let's go

**Pull request merged**
