### PR TITLE
No more DROP TABLE on Doctrine embeddable class

### PR DESCRIPTION
**Pull request by abuadella**
Put back #39

### CODE REVIEW

**Comment by gmorel** [comment]
My bad

:+1:

**Comment by tyx** [comment]
:+1:

**Comment by gmorel** [comment]
@tyx Could you add a tag please ?

**Comment by tyx** [comment]
Here it is https://github.com/rezzza/alice-extension/releases/tag/v2.0.1

**Comment by gmorel** [comment]
Thanks :exclamation:

**Pull request merged**
